#!/usr/bin/env bash
## Linux update && upgrade
sudo apt update && sudo apt upgrade -y
## need to enable a dedicated PPA with the following command
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
##  Install Haproxy
sudo apt install haproxy
## change property - ubuntu
sudo chown -R ubuntu /var/www
## Active modo execute in haproxy.cfg
sudo chmod 777 /etc/haproxy/haproxy.cfg
## Initialization the services haproxy
sudo service haproxy start
## Adding lines in haproxy.cfg
echo -e "# Configure Frontend listen all *:80 and solve with Backend" >> /etc/haproxy/haproxy.cfg
echo -e "frontend Frontend" >> /etc/haproxy/haproxy.cfg
echo -e "\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tmode http" >> /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend Backend" >> /etc/haproxy/haproxy.cfg
echo -e "# Configure the list the all server" >> /etc/haproxy/haproxy.cfg
echo -e "backend Backend" >> /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 3377-web-01 34.74.254.2:80 check" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 3377-web-02 52.207.225.1:80 check" >> /etc/haproxy/haproxy.cfg
## Restart services haproxy
sudo service haproxy restart
## Linux update && upgrade
sudo apt update && sudo apt upgrade -y
