#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
n=1
while (( n<=100 ))
do
    if (( n % 15 == 0 ))
    then
	echo "FizzBuzz"
    elif (( n % 3 == 0 ))
    then
	echo "Fizz"
    elif (( n % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo $n
    fi
    n=$(( n+1 ))
done
