#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
h=0
m=1
while (( h<=12 ))
do
    echo "Hour:" $h
    m=1
    while (( m <= 59 ))
    do
	echo $m
	m=$(( m+1 ))
    done
    h=$(( h+1 ))
done
