#!/usr/bin/env bash
#Change your home IP
cp /etc/hosts ~/hosts.new
chmod a+w ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
