#!/usr/bin/env bash
chown nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# Restart service nginx
sudo -u nginx service nginx restart
